In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
data=pd.read_csv('Absenteeism_data.csv')


In [9]:
df=data.copy()
df.head()

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   ID                         700 non-null    int64  
 1   Reason for Absence         700 non-null    int64  
 2   Date                       700 non-null    object 
 3   Transportation Expense     700 non-null    int64  
 4   Distance to Work           700 non-null    int64  
 5   Age                        700 non-null    int64  
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64  
 8   Education                  700 non-null    int64  
 9   Children                   700 non-null    int64  
 10  Pets                       700 non-null    int64  
 11  Absenteeism Time in Hours  700 non-null    int64  
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB


# Data Preparation

In [11]:
df.drop(columns='ID',inplace=True)

In [12]:
df.head(2)

Reason for Absence        Date  Transportation Expense  Distance to Work  \
0                  26  07/07/2015                     289                36   
1                   0  14/07/2015                     118                13   

   Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0   33                  239.554               30          1         2     1   
1   50                  239.554               31          1         1     0   

   Absenteeism Time in Hours  
0                          4  
1                          0

In [13]:
df['Reason for Absence'].min()

0

In [14]:
df['Reason for Absence'].max()

28

In [15]:
df['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16], dtype=int64)

In [17]:
len(df['Reason for Absence'].unique())

28

In [18]:
sorted(df['Reason for Absence'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

In [28]:
# Encoding the Reason for Absence column
reasons=pd.get_dummies(df['Reason for Absence'])
reasons.head()

0   1   2   3   4   5   6   7   8   9   ...  18  19  21  22  23  24  25  \
0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1   1   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
3   0   0   0   0   0   0   0   1   0   0  ...   0   0   0   0   0   0   0   
4   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   

   26  27  28  
0   1   0   0  
1   0   0   0  
2   0   0   0  
3   0   0   0  
4   0   0   0  

[5 rows x 28 columns]

In [29]:
reasons['check']=reasons.sum(axis=1)
reasons.head()

0  1  2  3  4  5  6  7  8  9  ...  19  21  22  23  24  25  26  27  28  \
0  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   1   0   0   
1  1  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
2  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   1   0   0   0   0   0   
3  0  0  0  0  0  0  0  1  0  0  ...   0   0   0   0   0   0   0   0   0   
4  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   1   0   0   0   0   0   

   check  
0      1  
1      1  
2      1  
3      1  
4      1  

[5 rows x 29 columns]

In [30]:
reasons['check'].sum(axis=0)

700

In [31]:
len(reasons)

700

In [32]:
reasons['check'].unique()

array([1], dtype=int64)

In [33]:
reasons.drop(columns='check',inplace=True)
reasons.head()

0   1   2   3   4   5   6   7   8   9   ...  18  19  21  22  23  24  25  \
0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1   1   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
3   0   0   0   0   0   0   0   1   0   0  ...   0   0   0   0   0   0   0   
4   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   

   26  27  28  
0   1   0   0  
1   0   0   0  
2   0   0   0  
3   0   0   0  
4   0   0   0  

[5 rows x 28 columns]

In [34]:
reasons=pd.get_dummies(df['Reason for Absence'],drop_first=True)
reasons.head()

1   2   3   4   5   6   7   8   9   10  ...  18  19  21  22  23  24  25  \
0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
3   0   0   0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   0   
4   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   

   26  27  28  
0   1   0   0  
1   0   0   0  
2   0   0   0  
3   0   0   0  
4   0   0   0  

[5 rows x 27 columns]

In [37]:
# Grouping the reasons columns
reason_class1=reasons.loc[:,1:14].max(axis=1)
reason_class2=reasons.loc[:,15:17].max(axis=1)
reason_class3=reasons.loc[:,18:21].max(axis=1)
reason_class4=reasons.loc[:,22:].max(axis=1)

In [38]:
reason_class1

0      0
1      0
2      0
3      1
4      0
      ..
695    1
696    1
697    1
698    0
699    0
Length: 700, dtype: uint8

In [39]:
df=pd.concat([reason_class1,reason_class2,reason_class3,reason_class4,df],axis=1)
df.head()

0  1  2  3  Reason for Absence        Date  Transportation Expense  \
0  0  0  0  1                  26  07/07/2015                     289   
1  0  0  0  0                   0  14/07/2015                     118   
2  0  0  0  1                  23  15/07/2015                     179   
3  1  0  0  0                   7  16/07/2015                     279   
4  0  0  0  1                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [40]:
df.drop(columns='Reason for Absence',inplace=True)
df.head()

0  1  2  3        Date  Transportation Expense  Distance to Work  Age  \
0  0  0  0  1  07/07/2015                     289                36   33   
1  0  0  0  0  14/07/2015                     118                13   50   
2  0  0  0  1  15/07/2015                     179                51   38   
3  1  0  0  0  16/07/2015                     279                 5   39   
4  0  0  0  1  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

In [44]:
df=df.rename(columns={0:'Reason_1',1:'Reason_2',2:'Reason_3',3:'Reason_4'})
df.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  07/07/2015                     289   
1         0         0         0         0  14/07/2015                     118   
2         0         0         0         1  15/07/2015                     179   
3         1         0         0         0  16/07/2015                     279   
4         0         0         0         1  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [72]:
# creating a checkpoint
df_reasons_processed=df.copy()

In [73]:
# Let's process Date column
type(df_reasons_processed['Date'][0])

str

In [74]:
df_reasons_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Reason_1                   700 non-null    uint8  
 1   Reason_2                   700 non-null    uint8  
 2   Reason_3                   700 non-null    uint8  
 3   Reason_4                   700 non-null    uint8  
 4   Date                       700 non-null    object 
 5   Transportation Expense     700 non-null    int64  
 6   Distance to Work           700 non-null    int64  
 7   Age                        700 non-null    int64  
 8   Daily Work Load Average    700 non-null    float64
 9   Body Mass Index            700 non-null    int64  
 10  Education                  700 non-null    int64  
 11  Children                   700 non-null    int64  
 12  Pets                       700 non-null    int64  
 13  Absenteeism Time in Hours  700 non-null    int64  

In [75]:
# let's convert these to datetime object
df_reasons_processed['Date']=pd.to_datetime(df['Date'],format='%d/%m/%Y')

In [76]:
df_reasons_processed.head(2)

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0

In [77]:
type(df_reasons_processed['Date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [78]:
df_reasons_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype         
---  ------                     --------------  -----         
 0   Reason_1                   700 non-null    uint8         
 1   Reason_2                   700 non-null    uint8         
 2   Reason_3                   700 non-null    uint8         
 3   Reason_4                   700 non-null    uint8         
 4   Date                       700 non-null    datetime64[ns]
 5   Transportation Expense     700 non-null    int64         
 6   Distance to Work           700 non-null    int64         
 7   Age                        700 non-null    int64         
 8   Daily Work Load Average    700 non-null    float64       
 9   Body Mass Index            700 non-null    int64         
 10  Education                  700 non-null    int64         
 11  Children                   700 non-null    int64         
 12  Pets    

In [79]:
# Extracting the Month Value
list_months=[]
for i in range(len(df_reasons_processed)):
    list_months.append(df_reasons_processed['Date'][i].month)

In [80]:
len(list_months)

700

In [81]:
df_reasons_processed['Month Value']=list_months

In [82]:
df_reasons_processed.head(2)

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   

   Children  Pets  Absenteeism Time in Hours  Month Value  
0         2     1                          4            7  
1         1     0                          0            7

In [83]:
# Extracting the Day of the Week
def date_to_weekday(date_value):
    return date_value.weekday()

In [84]:
df_reasons_processed['Day of the Week']=df_reasons_processed['Date'].apply(date_to_weekday)

In [85]:
df_reasons_processed.head(2)

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1

In [86]:
df_reasons_processed.drop(columns='Date',inplace=True)

In [87]:
df_reasons_processed.head(2)

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1

In [88]:
df_reasons_processed.columns

Index(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets', 'Absenteeism Time in Hours', 'Month Value', 'Day of the Week'],
      dtype='object')

In [89]:
# Reordering the columns
column_names_reordered=['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Month Value','Day of the Week',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets', 'Absenteeism Time in Hours']
df_reasons_processed=df_reasons_processed[column_names_reordered]

In [90]:
df_reasons_processed.head(2)

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          1         2     1                          4  
1               31          1         1     0                          0

In [91]:
# Creating another checkpoint
df_reasons_date_processed=df_reasons_processed.copy()

In [92]:
df_reasons_date_processed['Education'].unique()

array([1, 3, 2, 4], dtype=int64)

In [93]:
df_reasons_date_processed['Education'].value_counts()

1    583
3     73
2     40
4      4
Name: Education, dtype: int64

In [94]:
# Encoding the Education Column
df_reasons_date_processed['Education']=df_reasons_date_processed['Education'].map({1:0,2:1,3:1,4:1})

In [95]:
df_reasons_date_processed['Education'].unique()

array([0, 1], dtype=int64)

In [96]:
df_reasons_date_processed['Education'].value_counts()

0    583
1    117
Name: Education, dtype: int64

In [97]:
# Final checkpoint
df_processed=df_reasons_date_processed.copy()

In [98]:
df_processed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [99]:
df_processed.to_csv('Absenteeism_preprocessed.csv',index=False)

# Model Building-Logistic Regression

In [100]:
import numpy as np
import pandas as pd

In [101]:
df=pd.read_csv('Absenteeism_preprocessed.csv')
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [102]:
df['Absenteeism Time in Hours'].unique()

array([  4,   0,   2,   8,  40,   1,   7,   3,  32,   5,  16,  24,  64,
        56,  80, 120, 112, 104,  48], dtype=int64)

In [103]:
df['Absenteeism Time in Hours'].median()

3.0

In [104]:
excessive_absenteeism=np.where(df['Absenteeism Time in Hours']>3,1,0)

In [105]:
df['excessive_absenteeism']=excessive_absenteeism

In [106]:
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   excessive_absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [107]:
df.drop(columns='Absenteeism Time in Hours',inplace=True)

In [108]:
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  excessive_absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

In [109]:
df['excessive_absenteeism'].value_counts()

0    381
1    319
Name: excessive_absenteeism, dtype: int64

In [10]:
df['Education'].unique()  #no need to apply feature scaling bcz already b/w -3 & +3

array([0, 1], dtype=int64)

In [11]:
df['Children'].unique()   # have to apply feature scaling

array([2, 1, 0, 4, 3], dtype=int64)

In [12]:
df['Pet'].unique()     # have to apply feature scaling

array([1, 0, 4, 2, 5, 8], dtype=int64)

In [13]:
df['Day of the Week'].unique()     # have to apply feature scaling

array([1, 2, 3, 4, 6, 0, 5], dtype=int64)

In [14]:
# Thus we've to apply feature scaling to all the columns except the Reason's & Education Column. Now since Education Column is
# in the middle of a df,so as to apply scaling conveniently we'll extract the education values in a variable,then drop it 
# from our df & finally insert the extracted values of eduction at our desired location in the df.
# insert 
edu=df['Education']
edu

0      0
1      0
2      0
3      0
4      0
      ..
695    1
696    0
697    1
698    1
699    0
Name: Education, Length: 700, dtype: int64

In [15]:
df.drop(columns='Education',inplace=True)
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Children  Pet  excessive_absenteeism  
0               30         2    1                      1  
1               31         1    0                      0  
2               31         0    0                      0  
3               24         2    0                      1  
4               30         2    1                      0

In [16]:
df.insert(4,'Education',edu)

In [17]:
# Now feature scaling can be applied conveniently further down
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Education  Month Value  \
0         0         0         0         1          0            7   
1         0         0         0         0          0            7   
2         0         0         0         1          0            7   
3         1         0         0         0          0            7   
4         0         0         0         1          0            7   

   Day of the Week  Transportation Expense  Distance to Work  Age  \
0                1                     289                36   33   
1                1                     118                13   50   
2                2                     179                51   38   
3                3                     279                 5   39   
4                3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Children  Pet  \
0                  239.554               30         2    1   
1                  239.554               31         1    0   
2                  239.554               31         0    0   
3                  239.554               24         2    0   
4                  239.554               30         2    1   

   excessive_absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [18]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [19]:
print(y)

[1 0 0 1 0 0 1 1 1 1 1 1 1 0 1 1 0 1 1 0 1 0 1 1 1 1 0 1 1 0 1 1 1 1 0 0 1
 1 1 1 0 1 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0
 1 1 0 1 0 0 0 0 1 1 1 1 1 1 0 1 0 1 0 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0 0 1 0
 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 0 0
 0 1 0 1 0 0 1 0 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 0 1 0 1 1 0 1 0 0 0 0
 0 0 1 0 0 1 1 0 0 1 0 1 1 1 1 1 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 1 1
 1 1 1 1 1 1 1 1 0 1 1 0 0 0 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 0 1 0 0 1 0 0 1
 1 0 1 0 0 0 0 0 1 1 1 1 0 1 0 1 0 0 0 1 1 0 1 1 1 0 0 0 1 1 1 1 1 1 0 0 1
 0 1 0 1 0 1 0 0 0 0 0 1 1 0 1 0 0 0 1 1 0 1 0 1 0 0 1 1 1 0 0 0 0 0 1 1 1
 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 1 1 1 0 0 1 1 1 0 0 1 1 1 1 1 0 0 0
 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1 0 0 1 0 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 0 0
 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0
 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 1 1 1 1 1 1 1 1 0 0 1 0 0 1 1 1 0 0 0 1
 0 1 1 1 1 1 1 1 1 1 0 1 

In [20]:
#splitting the dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [21]:
x_train

array([[ 0.,  0.,  0., ..., 28.,  0.,  0.],
       [ 0.,  0.,  0., ..., 38.,  1.,  0.],
       [ 0.,  0.,  0., ..., 31.,  0.,  0.],
       ...,
       [ 0.,  0.,  1., ..., 27.,  1.,  4.],
       [ 0.,  0.,  0., ..., 24.,  1.,  2.],
       [ 0.,  0.,  0., ..., 19.,  0.,  0.]])

In [22]:
x_test

array([[ 0.,  0.,  0., ..., 31.,  1.,  0.],
       [ 0.,  0.,  0., ..., 19.,  0.,  0.],
       [ 0.,  0.,  0., ..., 21.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ..., 31.,  0.,  0.],
       [ 0.,  0.,  0., ..., 19.,  0.,  0.],
       [ 0.,  0.,  0., ..., 25.,  0.,  0.]])

In [23]:
y_test

array([0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1])

In [24]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,5:]=sc.fit_transform(x_train[:,5:])
x_test[:,5:]=sc.transform(x_test[:,5:])

In [25]:
import sys
np.set_printoptions(threshold=sys.maxsize)
x_train

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  6.46391837e-01,
         2.06105063e+00, -1.56395114e+00, -1.37224894e+00,
         1.00136689e-01, -7.73123896e-01,  2.80561176e-01,
        -9.12334874e-01, -5.85102704e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  6.46391837e-01,
         3.44359971e-01,  1.78263202e-01, -6.98398181e-01,
         1.04524702e+00,  5.56296740e-01,  2.58767217e+00,
         3.27001747e-03, -5.85102704e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00, -2.39365330e-01,
        -2.27870248e-01, -6.55617168e-01,  1.39053918e+00,
         2.57655077e-01, -4.70922117e-01,  9.72694474e-01,
        -9.12334874e-01, -5.85102704e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00, -1.42037489e+00,
         9.16590191e-01, -6.55617168e-01,  1.

In [26]:
x_test

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  9.41644226e-01,
         3.44359971e-01, -1.56395114e+00, -1.17009371e+00,
         2.14787573e+00, -1.79735618e-01,  9.72694474e-01,
         3.27001747e-03, -5.85102704e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  1.00000000e+00, -1.42037489e+00,
        -2.27870248e-01, -6.55617168e-01, -2.94087725e-01,
        -1.00249202e+00, -1.99094277e-01, -1.79583872e+00,
        -9.12334874e-01, -5.85102704e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00, -1.71562727e+00,
         9.16590191e-01, -5.81163564e-01,  7.84073492e-01,
        -1.47504719e+00, -7.73123896e-01, -1.33441652e+00,
        -9.12334874e-01, -5.85102704e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  3.51139448e-01,
         3.44359971e-01,  1.01214357e+00,  4.

In [27]:
#training the model
from sklearn.linear_model import LogisticRegression
reg=LogisticRegression(random_state=0)
reg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [28]:
y_pred=reg.predict(x_test)

In [29]:
#calculating the accuracy
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)
# Thus with our training mechanism,we got 77% accuracy which is also confirmed with the K-Fold and this is better than that of
# Udemy's Accuracy which was only 73%


[[58 14]
 [18 50]]


0.7714285714285715

In [30]:
# Applying K-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies=cross_val_score(estimator=reg,X=x_train,y=y_train,cv=10)
print('Accuracy is: {:.2f} %'.format(accuracies.mean()*100))
print('StDev is: {:.2f} %'.format(accuracies.std()*100))

Accuracy is: 75.00 %
StDev is: 4.79 %


In [31]:
# Applying Grid Search
from sklearn.model_selection import GridSearchCV
parameters=[{'C':[0.25,0.5,0.75,1.0],'penalty':['l2'],'solver':['newton-cg','lbfgs','sag'],'max_iter':[50,75,100,125,150],'multi_class':['auto','ovr','multinomial']},
            {'C':[0.25,0.5,0.75,1.0],'multi_class':['multinomial'],'solver':['newton-cg','lbfgs','sag','saga'],'max_iter':[50,75,100,125,150]}]
grid_search=GridSearchCV(estimator=reg,param_grid=parameters,scoring='accuracy',cv=10,n_jobs=-1)
grid_search.fit(x_train,y_train)
best_accuracy=grid_search.best_score_
best_parameters=grid_search.best_params_
print('Best Accuracy is: {:.2f} %'.format(best_accuracy*100))
print('Best Parameters are:',best_parameters)

Best Accuracy is: 75.00 %
Best Parameters are: {'C': 0.5, 'max_iter': 50, 'multi_class': 'multinomial', 'penalty': 'l2', 'solver': 'newton-cg'}


In [79]:
# single prediction....?  Few are scaled and few aren;t...?


# KNN

In [32]:
import numpy as np
import pandas as pd

In [33]:
df=pd.read_csv('Absenteeism_preprocessed.csv')
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

In [34]:
Excessive_Absenteesim=np.where(df['Absenteeism Time in Hours']>3,1,0)

In [35]:
df['Excessive_Absenteesim']=Excessive_Absenteesim
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive_Absenteesim  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [36]:
df.drop(columns='Absenteeism Time in Hours',inplace=True)
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Excessive_Absenteesim  
0               30          0         2    1                      1  
1               31          0         1    0                      0  
2               31          0         0    0                      0  
3               24          0         2    0                      1  
4               30          0         2    1                      0

In [37]:
e=df['Education']
e

0      0
1      0
2      0
3      0
4      0
      ..
695    1
696    0
697    1
698    1
699    0
Name: Education, Length: 700, dtype: int64

In [38]:
df.drop(columns='Education',inplace=True)
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Children  Pet  Excessive_Absenteesim  
0               30         2    1                      1  
1               31         1    0                      0  
2               31         0    0                      0  
3               24         2    0                      1  
4               30         2    1                      0

In [39]:
df.insert(4,'Education',e)

In [40]:
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Education  Month Value  \
0         0         0         0         1          0            7   
1         0         0         0         0          0            7   
2         0         0         0         1          0            7   
3         1         0         0         0          0            7   
4         0         0         0         1          0            7   

   Day of the Week  Transportation Expense  Distance to Work  Age  \
0                1                     289                36   33   
1                1                     118                13   50   
2                2                     179                51   38   
3                3                     279                 5   39   
4                3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Children  Pet  \
0                  239.554               30         2    1   
1                  239.554               31         1    0   
2                  239.554               31         0    0   
3                  239.554               24         2    0   
4                  239.554               30         2    1   

   Excessive_Absenteesim  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [41]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [42]:
#splitting the dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [43]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,:5:]=sc.fit_transform(x_train[:,:5:])
x_test[:,:5:]=sc.transform(x_test[:,:5:])

In [44]:
#training the KNN Model
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=10,metric='minkowski',p=2)
classifier.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [45]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred=classifier.predict(x_test)
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

# Thus KNN model is not performing well

[[56 16]
 [35 33]]


0.6357142857142857

In [46]:
# Applying K-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies=cross_val_score(estimator=classifier,X=x_train,y=y_train,cv=10)
print('Accuracy is: {:.2f} %'.format(accuracies.mean()*100))
print('StDev is: {:.2f} %'.format(accuracies.std()*100))

Accuracy is: 65.00 %
StDev is: 4.87 %


# SVM Model


In [47]:
import numpy as np
import pandas as pd

In [48]:
df=pd.read_csv('Absenteeism_preprocessed.csv')
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

In [49]:
Excessive_Absenteesim=np.where(df['Absenteeism Time in Hours']>3,1,0)

In [50]:
df['Excessive_Absenteesim']=Excessive_Absenteesim
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive_Absenteesim  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [51]:
df.drop(columns='Absenteeism Time in Hours',inplace=True)
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Excessive_Absenteesim  
0               30          0         2    1                      1  
1               31          0         1    0                      0  
2               31          0         0    0                      0  
3               24          0         2    0                      1  
4               30          0         2    1                      0

In [52]:
e=df['Education']
e

0      0
1      0
2      0
3      0
4      0
      ..
695    1
696    0
697    1
698    1
699    0
Name: Education, Length: 700, dtype: int64

In [53]:
df.drop(columns='Education',inplace=True)
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Children  Pet  Excessive_Absenteesim  
0               30         2    1                      1  
1               31         1    0                      0  
2               31         0    0                      0  
3               24         2    0                      1  
4               30         2    1                      0

In [54]:
df.insert(4,'Education',e)

In [55]:
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Education  Month Value  \
0         0         0         0         1          0            7   
1         0         0         0         0          0            7   
2         0         0         0         1          0            7   
3         1         0         0         0          0            7   
4         0         0         0         1          0            7   

   Day of the Week  Transportation Expense  Distance to Work  Age  \
0                1                     289                36   33   
1                1                     118                13   50   
2                2                     179                51   38   
3                3                     279                 5   39   
4                3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Children  Pet  \
0                  239.554               30         2    1   
1                  239.554               31         1    0   
2                  239.554               31         0    0   
3                  239.554               24         2    0   
4                  239.554               30         2    1   

   Excessive_Absenteesim  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [56]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [57]:
#splitting the dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [58]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,:5:]=sc.fit_transform(x_train[:,:5:])
x_test[:,:5:]=sc.transform(x_test[:,:5:])

In [59]:
from sklearn.svm import SVC
classifier=SVC(kernel='linear',random_state=0)
classifier.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [60]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred=classifier.predict(x_test)
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

# SVM is performing better than Udemy and above Logistic reg too

[[59 13]
 [16 52]]


0.7928571428571428

In [61]:
# Applying K-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies=cross_val_score(estimator=classifier,X=x_train,y=y_train,cv=10)
print('Accuracy is: {:.2f} %'.format(accuracies.mean()*100))
print('StDev is: {:.2f} %'.format(accuracies.std()*100))

Accuracy is: 73.93 %
StDev is: 4.74 %


In [ ]:
# Applying Grid Search
#from sklearn.model_selection import GridSearchCV
#parameters=[{'C':[0.25,0.5,0.75,1.0],'kernel':['linear']},
#            {'C':[0.25,0.5,0.75,1.0],'kernel':['poly','rbf','sigmoid'],'gamma':[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]}]
#grid_search=GridSearchCV(estimator=classifier,param_grid=parameters,scoring='accuracy',cv=10,n_jobs=-1)
#grid_search.fit(x_train,y_train)
#best_accuracy=grid_search.best_score_
#best_parameters=grid_search.best_params_
#print('Best Accuracy is: {:.2f} %'.format(best_accuracy*100))
#print('Best Parameters are:',best_parameters)

In [140]:
# R-Square
classifier.score(x_train,y_train)

0.7589285714285714

In [141]:
# Coefficients
classifier.coef_

array([[ 1.93715275e+00,  2.17721996e-01,  1.35391263e+00,
         1.20439257e+00, -2.38182949e-03,  1.10422003e-03,
        -1.37107148e-02,  8.37300330e-03,  1.01331505e-02,
        -3.11761885e-02, -3.13555691e-04,  2.73388819e-02,
         3.68846454e-01, -3.19276305e-01]])

# Kernel SVM


In [138]:
import numpy as np
import pandas as pd

In [142]:
df=pd.read_csv('Absenteeism_preprocessed.csv')
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

In [143]:
Excessive_Absenteesim=np.where(df['Absenteeism Time in Hours']>3,1,0)

In [144]:
df['Excessive_Absenteesim']=Excessive_Absenteesim
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive_Absenteesim  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [145]:
df.drop(columns='Absenteeism Time in Hours',inplace=True)
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Excessive_Absenteesim  
0               30          0         2    1                      1  
1               31          0         1    0                      0  
2               31          0         0    0                      0  
3               24          0         2    0                      1  
4               30          0         2    1                      0

In [146]:
e=df['Education']
e

0      0
1      0
2      0
3      0
4      0
      ..
695    1
696    0
697    1
698    1
699    0
Name: Education, Length: 700, dtype: int64

In [147]:
df.drop(columns='Education',inplace=True)
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Children  Pet  Excessive_Absenteesim  
0               30         2    1                      1  
1               31         1    0                      0  
2               31         0    0                      0  
3               24         2    0                      1  
4               30         2    1                      0

In [148]:
df.insert(4,'Education',e)

In [149]:
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Education  Month Value  \
0         0         0         0         1          0            7   
1         0         0         0         0          0            7   
2         0         0         0         1          0            7   
3         1         0         0         0          0            7   
4         0         0         0         1          0            7   

   Day of the Week  Transportation Expense  Distance to Work  Age  \
0                1                     289                36   33   
1                1                     118                13   50   
2                2                     179                51   38   
3                3                     279                 5   39   
4                3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Children  Pet  \
0                  239.554               30         2    1   
1                  239.554               31         1    0   
2                  239.554               31         0    0   
3                  239.554               24         2    0   
4                  239.554               30         2    1   

   Excessive_Absenteesim  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [150]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [151]:
#splitting the dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [152]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,:5:]=sc.fit_transform(x_train[:,:5:])
x_test[:,:5:]=sc.transform(x_test[:,:5:])

In [153]:
#training
from sklearn.svm import SVC
classifier=SVC(kernel='rbf',random_state=0)
classifier.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [154]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred=classifier.predict(x_test)
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

#

[[66  6]
 [48 20]]


0.6142857142857143

In [155]:
# Applying K-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies=cross_val_score(estimator=classifier,X=x_train,y=y_train,cv=10)
print('Accuracy is: {:.2f} %'.format(accuracies.mean()*100))
print('StDev is: {:.2f} %'.format(accuracies.std()*100))

Accuracy is: 60.71 %
StDev is: 5.92 %


In [156]:
# R-Square
classifier.score(x_train,y_train)

0.6142857142857143

# Naive Bayes

In [157]:
import numpy as np
import pandas as pd

In [158]:
df=pd.read_csv('Absenteeism_preprocessed.csv')
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

In [159]:
Excessive_Absenteesim=np.where(df['Absenteeism Time in Hours']>3,1,0)

In [160]:
df['Excessive_Absenteesim']=Excessive_Absenteesim
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive_Absenteesim  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [161]:
df.drop(columns='Absenteeism Time in Hours',inplace=True)
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Excessive_Absenteesim  
0               30          0         2    1                      1  
1               31          0         1    0                      0  
2               31          0         0    0                      0  
3               24          0         2    0                      1  
4               30          0         2    1                      0

In [162]:
e=df['Education']
e

0      0
1      0
2      0
3      0
4      0
      ..
695    1
696    0
697    1
698    1
699    0
Name: Education, Length: 700, dtype: int64

In [163]:
df.drop(columns='Education',inplace=True)
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Children  Pet  Excessive_Absenteesim  
0               30         2    1                      1  
1               31         1    0                      0  
2               31         0    0                      0  
3               24         2    0                      1  
4               30         2    1                      0

In [164]:
df.insert(4,'Education',e)

In [165]:
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Education  Month Value  \
0         0         0         0         1          0            7   
1         0         0         0         0          0            7   
2         0         0         0         1          0            7   
3         1         0         0         0          0            7   
4         0         0         0         1          0            7   

   Day of the Week  Transportation Expense  Distance to Work  Age  \
0                1                     289                36   33   
1                1                     118                13   50   
2                2                     179                51   38   
3                3                     279                 5   39   
4                3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Children  Pet  \
0                  239.554               30         2    1   
1                  239.554               31         1    0   
2                  239.554               31         0    0   
3                  239.554               24         2    0   
4                  239.554               30         2    1   

   Excessive_Absenteesim  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [166]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [167]:
#splitting the dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [168]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,:5:]=sc.fit_transform(x_train[:,:5:])
x_test[:,:5:]=sc.transform(x_test[:,:5:])

In [173]:
#training
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [174]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred=classifier.predict(x_test)
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

#

[[56 16]
 [19 49]]


0.75

In [175]:
# Applying K-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies=cross_val_score(estimator=classifier,X=x_train,y=y_train,cv=10)
print('Accuracy is: {:.2f} %'.format(accuracies.mean()*100))
print('StDev is: {:.2f} %'.format(accuracies.std()*100))

Accuracy is: 71.07 %
StDev is: 5.97 %


In [176]:
# R-Square
classifier.score(x_train,y_train)

0.7232142857142857

# Decision Trees

In [177]:
import numpy as np
import pandas as pd

In [178]:
df=pd.read_csv('Absenteeism_preprocessed.csv')
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

In [179]:
Excessive_Absenteesim=np.where(df['Absenteeism Time in Hours']>3,1,0)

In [180]:
df['Excessive_Absenteesim']=Excessive_Absenteesim
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive_Absenteesim  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [181]:
df.drop(columns='Absenteeism Time in Hours',inplace=True)
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Excessive_Absenteesim  
0               30          0         2    1                      1  
1               31          0         1    0                      0  
2               31          0         0    0                      0  
3               24          0         2    0                      1  
4               30          0         2    1                      0

In [182]:
e=df['Education']
e

0      0
1      0
2      0
3      0
4      0
      ..
695    1
696    0
697    1
698    1
699    0
Name: Education, Length: 700, dtype: int64

In [184]:
df.drop(columns='Education',inplace=True)
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Children  Pet  Excessive_Absenteesim  
0               30         2    1                      1  
1               31         1    0                      0  
2               31         0    0                      0  
3               24         2    0                      1  
4               30         2    1                      0

In [185]:
df.insert(4,'Education',e)

In [186]:
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Education  Month Value  \
0         0         0         0         1          0            7   
1         0         0         0         0          0            7   
2         0         0         0         1          0            7   
3         1         0         0         0          0            7   
4         0         0         0         1          0            7   

   Day of the Week  Transportation Expense  Distance to Work  Age  \
0                1                     289                36   33   
1                1                     118                13   50   
2                2                     179                51   38   
3                3                     279                 5   39   
4                3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Children  Pet  \
0                  239.554               30         2    1   
1                  239.554               31         1    0   
2                  239.554               31         0    0   
3                  239.554               24         2    0   
4                  239.554               30         2    1   

   Excessive_Absenteesim  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [187]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [188]:
#splitting the dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [189]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,:5:]=sc.fit_transform(x_train[:,:5:])
x_test[:,:5:]=sc.transform(x_test[:,:5:])

In [190]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [191]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred=classifier.predict(x_test)
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

#

[[58 14]
 [26 42]]


0.7142857142857143

In [192]:
# Applying K-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies=cross_val_score(estimator=classifier,X=x_train,y=y_train,cv=10)
print('Accuracy is: {:.2f} %'.format(accuracies.mean()*100))
print('StDev is: {:.2f} %'.format(accuracies.std()*100))

Accuracy is: 69.82 %
StDev is: 6.61 %


In [193]:
# R-Square
classifier.score(x_train,y_train)

0.9857142857142858

# Random Forest

In [194]:
import numpy as np
import pandas as pd

In [195]:
df=pd.read_csv('Absenteeism_preprocessed.csv')
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

In [196]:
Excessive_Absenteesim=np.where(df['Absenteeism Time in Hours']>3,1,0)

In [197]:
df['Excessive_Absenteesim']=Excessive_Absenteesim
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive_Absenteesim  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [198]:
df.drop(columns='Absenteeism Time in Hours',inplace=True)
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Excessive_Absenteesim  
0               30          0         2    1                      1  
1               31          0         1    0                      0  
2               31          0         0    0                      0  
3               24          0         2    0                      1  
4               30          0         2    1                      0

In [199]:
e=df['Education']
e

0      0
1      0
2      0
3      0
4      0
      ..
695    1
696    0
697    1
698    1
699    0
Name: Education, Length: 700, dtype: int64

In [200]:
df.drop(columns='Education',inplace=True)
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Children  Pet  Excessive_Absenteesim  
0               30         2    1                      1  
1               31         1    0                      0  
2               31         0    0                      0  
3               24         2    0                      1  
4               30         2    1                      0

In [201]:
df.insert(4,'Education',e)

In [202]:
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Education  Month Value  \
0         0         0         0         1          0            7   
1         0         0         0         0          0            7   
2         0         0         0         1          0            7   
3         1         0         0         0          0            7   
4         0         0         0         1          0            7   

   Day of the Week  Transportation Expense  Distance to Work  Age  \
0                1                     289                36   33   
1                1                     118                13   50   
2                2                     179                51   38   
3                3                     279                 5   39   
4                3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Children  Pet  \
0                  239.554               30         2    1   
1                  239.554               31         1    0   
2                  239.554               31         0    0   
3                  239.554               24         2    0   
4                  239.554               30         2    1   

   Excessive_Absenteesim  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [203]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [204]:
#splitting the dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [205]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,:5:]=sc.fit_transform(x_train[:,:5:])
x_test[:,:5:]=sc.transform(x_test[:,:5:])

In [206]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
classifier.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [207]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred=classifier.predict(x_test)
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

#

[[58 14]
 [22 46]]


0.7428571428571429

In [208]:
# Applying K-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies=cross_val_score(estimator=classifier,X=x_train,y=y_train,cv=10)
print('Accuracy is: {:.2f} %'.format(accuracies.mean()*100))
print('StDev is: {:.2f} %'.format(accuracies.std()*100))

Accuracy is: 71.43 %
StDev is: 5.42 %


In [209]:
# R-Square
classifier.score(x_train,y_train)

0.9732142857142857